# Generated by Django 3.2.7 on 2021-09-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0003_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signupcustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
